name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  HELM_VALUES: ./helm-charts/docker-storage-web/values.uxsoft-cz-dev.yaml

jobs:
  build:
    timeout-minutes: 600
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions: 
      contents: write
      packages: write

    steps:
      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64 #linux/amd64,
          
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/${{ env.IMAGE_NAME }}:latest, ghcr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}
          platforms: linux/arm64 #linux/amd64, linux/arm64
          push: true
       
      - uses: actions/checkout@v4
        with:
          repository: 'uxsoft/infra-helm-charts'
          token: ${{ secrets.PAT }}
          ref: 'main'
          path: './helm-charts'
        
      - name: Update Helm Chart Docker Image Tag
        run: |
          sed -i "s/^  tag:.*/  tag: ${{ github.run_number }}/" ${{ env.HELM_VALUES }}
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./helm-charts
